name: f_sharp
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - ipykernel
    - notebook
    - jupyterlab
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - plotly
    - scipy
    - sympy
    - jupyter-client
    - ipython
